# Referencing this link: https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-nodejs
name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x' # Preferably use 22.9.x
      - run: npm ci

      - name: Create a build
        run: npm run build
      # TODO: Uncomment this part when we write tests
      #- run: npm test
